/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "primeFunct.h"

bool_t
xdr_token (XDR *xdrs, token *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->numberOfHops))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->initialTime))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numOfPrimes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->nextInt))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->numberOfHops);
			IXDR_PUT_LONG(buf, objp->initialTime);
			IXDR_PUT_LONG(buf, objp->numOfPrimes);
			IXDR_PUT_U_LONG(buf, objp->nextInt);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->numberOfHops))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->initialTime))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numOfPrimes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->nextInt))
				 return FALSE;
		} else {
			objp->numberOfHops = IXDR_GET_LONG(buf);
			objp->initialTime = IXDR_GET_LONG(buf);
			objp->numOfPrimes = IXDR_GET_LONG(buf);
			objp->nextInt = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->numberOfHops))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->initialTime))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numOfPrimes))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->nextInt))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TOKEN (XDR *xdrs, TOKEN *objp)
{
	register int32_t *buf;

	 if (!xdr_token (xdrs, objp))
		 return FALSE;
	return TRUE;
}
