/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRIMEFUNCT_H_RPCGEN
#define _PRIMEFUNCT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct token {
	int numberOfHops;
	int initialTime;
	int numOfPrimes;
	u_int nextInt;
};
typedef struct token token;

typedef token TOKEN;

#define PRIMEFINDER 0x200000FF
#define ONE 1

#if defined(__STDC__) || defined(__cplusplus)
#define isPrime 1
extern  TOKEN * isprime_1(TOKEN *, CLIENT *);
extern  TOKEN * isprime_1_svc(TOKEN *, struct svc_req *);
extern int primefinder_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define isPrime 1
extern  TOKEN * isprime_1();
extern  TOKEN * isprime_1_svc();
extern int primefinder_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_token (XDR *, token*);
extern  bool_t xdr_TOKEN (XDR *, TOKEN*);

#else /* K&R C */
extern bool_t xdr_token ();
extern bool_t xdr_TOKEN ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRIMEFUNCT_H_RPCGEN */
